# Ignition Vision Button Click Handler
# Generated by IGN Scripts
# Template: vision/button_click_handler
# Generated: 2025-06-09 19:04:14

"""
Button click handler for MainMenuButton
Navigation button to main menu with parameter passing
"""

# Imports
from java.util import Date
from java.text import SimpleDateFormat

def handle_button_click(event):
    """
    Handle button click event for MainMenuButton
    
    Args:
        event: The actionPerformed event object from Ignition
    """
    try:
        # Navigate to window: MainMenu
        params = {"user_id": "{Root Container.CurrentUser.text}", "timestamp": "{Root Container.CurrentTime.text}", "source_window": "Dashboard"}
        system.nav.openWindow("MainMenu", params)
        
        
        # Log the action
        logger = system.util.getLogger("NavigationHandler")
        logger.info("Button clicked: MainMenuButton")
        
    except Exception as e:
        # Error handling
        system.gui.errorBox("Error in button handler: %s" % str(e))
        
        # Log the error
        logger = system.util.getLogger("NavigationHandler")
        logger.error("Error in button click handler for MainMenuButton: %s", str(e))
        

# Bind this function to the button's actionPerformed event
# Component path: Root Container.Header.MenuButton
# Event: actionPerformed
# Function: handle_button_click 