%YAML 1.2
---
site_name: MCP Service Documentation
site_description: Documentation for the Machine Control Program (MCP) service
site_author: IGN Scripts Team
repo_url: https://github.com/reh3376/mcp
repo_name: reh3376/mcp

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Quick Start: getting-started/quickstart.md
  - API Reference:
      - Endpoints: api/endpoints.md
      - Models: api/models.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Docker: development/docker.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true
