name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [mcp, mcp-tools]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: |
        cd ${{ matrix.service }}
        uv venv
        source .venv/bin/activate
        if [ -f requirements.txt ]; then
          uv pip install -r requirements.txt
        fi
        uv pip install bandit safety

    - name: Run Bandit
      run: |
        cd ${{ matrix.service }}
        source .venv/bin/activate
        bandit -r src -f json -o bandit-results.json || true

    - name: Run Safety
      run: |
        cd ${{ matrix.service }}
        source .venv/bin/activate
        if [ -f requirements.txt ]; then
          safety check -r requirements.txt --json > safety-results.json || true
        else
          safety check --json > safety-results.json || true
        fi

    - name: Run pip-audit
      run: |
        cd ${{ matrix.service }}
        source .venv/bin/activate
        pip install pip-audit
        if [ -f requirements.txt ]; then
          pip-audit -r requirements.txt --format=json --output=pip-audit-results.json || true
        else
          pip-audit --format=json --output=pip-audit-results.json || true
        fi

    - name: Upload Bandit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bandit-results-${{ matrix.service }}
        path: ./${{ matrix.service }}/bandit-results.json

    - name: Upload Safety results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: safety-results-${{ matrix.service }}
        path: ./${{ matrix.service }}/safety-results.json

    - name: Upload pip-audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pip-audit-results-${{ matrix.service }}
        path: ./${{ matrix.service }}/pip-audit-results.json

    - name: Check for vulnerabilities
      if: failure()
      run: |
        echo "Security vulnerabilities found. Please check the workflow logs for details."
        echo "Review the uploaded artifacts for detailed security reports."
        exit 1 