name: Verify Token Access

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  verify-snyk:
    name: Verify Snyk Token
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Verify Snyk token
      run: |
        source .venv/bin/activate
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test

  verify-docker:
    name: Verify Docker Token
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Verify Docker access
      run: |
        docker pull ghcr.io/reh3376/mcp:latest || true
        docker pull ghcr.io/reh3376/mcp-tools:latest || true 